### ISSUE TITLE
Tests failed on main branch for osx-64 python 3.10 & python 3.8

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/ompl-feedstock#29]
Hiya @conda-forge/ompl @traversaro - there were some test failures, leading to issues: https://github.com/tesseract-robotics-packaging/tesseract-robotics-planning-feedstock/issues/2

/cc @johnwason

**Comment by traversaro** [comment]
Thanks for the issue, I restarted the CI, let's see if that works. I also requested a re-render in https://github.com/conda-forge/ompl-feedstock/pull/31 .

**Comment by traversaro** [comment]
The missing files were uploaded: https://anaconda.org/conda-forge/ompl/files, please reopen or open a new issue if problems persist.
