### ISSUE TITLE
Why is ppc64le disabled?

### ISSUE THREAD

**Issue by photex** [conda-forge/ompl-feedstock#5]
Is there a specific technical reason for not enabling ppc64le builds for this feedstock?

Thanks!

**Comment by wolfv** [comment]
nope. you can add a migration for packages you are interested in by adding it to this list: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt

then arm64 and ppc64le will be built for this repo! Once you send the PR, ping me and I'll merge it.

**Comment by Anthchirp** [comment]
@wolfv ping @ conda-forge/conda-forge-pinning-feedstock#853

**Comment by wolfv** [comment]
Thx @Anthchirp 

Looking forward to your other PR
